[package]
name = "array_tool"
version = "0.2.2"
authors = ["Daniel P. Clark <6ftdan@gmail.com>"]
description = "Helper methods for processing Array like collections"
homepage = "https://github.com/danielpclark/array_tool"
repository = "https://github.com/danielpclark/array_tool"
license-file = "MIT-LICENSE"
readme = "README.md"
